Repository FlytrapHub/venus-planner-be, pull requests merged in 2024-03, with the labels that each got.

#13 [chore] 테스트 컨테이너 환경 구축
  build.gradle
  src/main/resources/schema.sql
  src/test/java/com/flytrap/venusplanner/global/AcceptanceTest.java
  src/test/resources/application.yml
  src/test/resources/reset.sql
Labels: 🔧chore

#9 [feat] 로그인 API 및 회원가입 로직 추가
  build.gradle
  src/main/java/com/flytrap/venusplanner/api/auth_member/business/service/AuthMemberService.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/presentation/controller/AuthMemberController.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/presentation/dto/LoginDto.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/presentation/dto/SessionMember.java
  src/main/java/com/flytrap/venusplanner/api/member/domain/Member.java
  src/main/java/com/flytrap/venusplanner/api/member/domain/OAuthPlatform.java
  src/main/java/com/flytrap/venusplanner/api/member/domain/OAuthPlatformType.java
  src/main/java/com/flytrap/venusplanner/api/member/domain/OAuthPlatformTypeConverter.java
  src/main/java/com/flytrap/venusplanner/api/member/exception/UnknownOAuthPlatformType.java
  src/main/java/com/flytrap/venusplanner/api/member/infrastructure/repository/MemberRepository.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/api/OAuthProvider.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/dto/StandardizedUserResource.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: ✨feat

#10 [feat] 로그인 로직에 GitHub OAuth 인증 추가
  .gitignore
  build.gradle
  src/main/java/com/flytrap/venusplanner/VenusPlannerApplication.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/business/service/AuthMemberService.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/presentation/controller/AuthMemberController.java
  src/main/java/com/flytrap/venusplanner/global/auth/config/OAuthPropertiesConfig.java
  src/main/java/com/flytrap/venusplanner/global/auth/config/OAuthWebClientConfig.java
  src/main/java/com/flytrap/venusplanner/global/auth/exception/GitHubOAuthRequestException.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/api/GitHubOAuthProvider.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/dto/AccessTokenFromGitHub.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/dto/StandardizedUserResource.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/dto/UserEmailResourceFromGitHub.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/dto/UserResourceFromGitHub.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/properties/AuthSessionProperties.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/properties/GitHubOAuthProperties.java
  src/main/resources/application.yml
Labels: ✨feat

#12 [feat] 로그인 상태를 검증해 주는 ArgumentResolver 구현
  src/main/java/com/flytrap/venusplanner/api/auth_member/business/service/AuthMemberService.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/presentation/controller/AuthMemberController.java
  src/main/java/com/flytrap/venusplanner/global/auth/annotation/SignIn.java
  src/main/java/com/flytrap/venusplanner/global/auth/config/SignInArgumentResolverConfig.java
  src/main/java/com/flytrap/venusplanner/global/auth/dto/SessionMember.java
  src/main/java/com/flytrap/venusplanner/global/auth/exception/SessionMemberAuthException.java
  src/main/java/com/flytrap/venusplanner/global/auth/resolver/SignInArgumentResolver.java
Labels: ✨feat

#11 [feat] 로그아웃 API 구현
  src/main/java/com/flytrap/venusplanner/api/auth_member/business/service/AuthMemberService.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/presentation/controller/AuthMemberController.java
  src/main/java/com/flytrap/venusplanner/global/auth/annotation/SignIn.java
  src/main/java/com/flytrap/venusplanner/global/auth/config/SignInArgumentResolverConfig.java
  src/main/java/com/flytrap/venusplanner/global/auth/dto/SessionMember.java
  src/main/java/com/flytrap/venusplanner/global/auth/exception/SessionMemberAuthException.java
  src/main/java/com/flytrap/venusplanner/global/auth/resolver/SignInArgumentResolver.java
Labels: ✨feat

#14 [feat] `PlanCategory` CRUD 기능 구현
  src/main/java/com/flytrap/venusplanner/api/plan_category/business/service/PlanCategoryService.java
  src/main/java/com/flytrap/venusplanner/api/plan_category/domain/ColorCode.java
  src/main/java/com/flytrap/venusplanner/api/plan_category/domain/PlanCategory.java
  src/main/java/com/flytrap/venusplanner/api/plan_category/infrastructure/repository/PlanCategoryRepository.java
  src/main/java/com/flytrap/venusplanner/api/plan_category/presentation/controller/PlanCategoryController.java
  src/main/java/com/flytrap/venusplanner/api/plan_category/presentation/dto/PlanCategoryCreateDto.java
  src/main/java/com/flytrap/venusplanner/api/plan_category/presentation/dto/request/PlanCategoryUpdateRequest.java
  src/main/java/com/flytrap/venusplanner/api/plan_category/presentation/dto/response/PlanCategoryReadResponse.java
  src/main/java/com/flytrap/venusplanner/global/annotation/color_code/ColorCode.java
  src/main/java/com/flytrap/venusplanner/global/annotation/color_code/ColorCodeValidator.java
Labels: ✨feat

#15 [test] `PlanCategory` CRUD 성공 케이스 테스트 코드 작성
  src/test/java/com/flytrap/venusplanner/acceptance/plan_category/PlanCategoryTest.java
  src/test/java/com/flytrap/venusplanner/global/fixture/PlanCategoryFixture.java
  src/test/java/com/flytrap/venusplanner/global/step/PlanCategoryStep.java
Labels: ✅test

#28 [feat] `Study` 생성 API 구현
  src/main/java/com/flytrap/venusplanner/api/access/domain/Permission.java
  src/main/java/com/flytrap/venusplanner/api/access/domain/Roll.java
  src/main/java/com/flytrap/venusplanner/api/member_study/business/service/MemberStudyService.java
  src/main/java/com/flytrap/venusplanner/api/member_study/domain/MemberStudy.java
  src/main/java/com/flytrap/venusplanner/api/member_study/infrastructure/repository/MemberStudyRepository.java
  src/main/java/com/flytrap/venusplanner/api/study/business/service/MemberStudyFacadeService.java
  src/main/java/com/flytrap/venusplanner/api/study/business/service/StudyService.java
  src/main/java/com/flytrap/venusplanner/api/study/domain/Study.java
  src/main/java/com/flytrap/venusplanner/api/study/presentation/controller/StudyController.java
  src/main/java/com/flytrap/venusplanner/api/study/presentation/dto/StudyCreateDto.java
  src/main/java/com/flytrap/venusplanner/global/config/JpaAuditConfig.java
  src/main/java/com/flytrap/venusplanner/global/entity/TimeAuditingBaseEntity.java
  src/main/resources/schema.sql
Labels: ✨feat

#30 [refactor] `plan` 관련 피드백 반영
  src/main/java/com/flytrap/venusplanner/api/plan/business/service/PlanService.java
  src/main/java/com/flytrap/venusplanner/api/plan/domain/Plan.java
  src/main/java/com/flytrap/venusplanner/api/plan/infrastructure/repository/PlanRepository.java
  src/main/java/com/flytrap/venusplanner/api/study_plan/business/service/StudyPlanFacadeService.java
  src/main/java/com/flytrap/venusplanner/api/study_plan/presentation/controller/StudyPlanController.java
Labels: ♻️refactor

#20 [refactor] 로그인, 회원가입 관련 피드백 반영
  src/main/java/com/flytrap/venusplanner/VenusPlannerApplication.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/business/service/AuthMemberService.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/exception/GitHubOAuthRequestException.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/infrastructure/dto/AccessTokenFromGitHub.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/infrastructure/dto/StandardizedUserResource.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/infrastructure/dto/UserEmailResourceFromGitHub.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/infrastructure/dto/UserResourceFromGitHub.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/infrastructure/external/GitHubOAuthProvider.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/infrastructure/external/OAuthProvider.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/presentation/controller/AuthMemberController.java
  src/main/java/com/flytrap/venusplanner/api/auth_member/presentation/dto/SignInDto.java
  src/main/java/com/flytrap/venusplanner/api/member/domain/Member.java
  src/main/java/com/flytrap/venusplanner/api/member/domain/OAuthPlatform.java
  src/main/java/com/flytrap/venusplanner/api/member/infrastructure/converter/OAuthPlatformTypeConverter.java
  src/main/java/com/flytrap/venusplanner/global/auth/config/OAuthPropertiesConfig.java
  src/main/java/com/flytrap/venusplanner/global/auth/config/OAuthWebClientConfig.java
  src/main/java/com/flytrap/venusplanner/global/auth/infrastructure/api/OAuthProvider.java
  src/main/java/com/flytrap/venusplanner/global/auth/properties/AuthSessionProperties.java
  src/main/java/com/flytrap/venusplanner/global/auth/properties/GitHubOAuthProperties.java
  src/main/java/com/flytrap/venusplanner/global/auth/resolver/SignInArgumentResolver.java
Labels: ♻️refactor
